[world]
name = "Echoes-of-the-Void"
description = "Echoes of the Void is a minimalist, grid-based puzzle-platformer set in a completely dark environment."
seed = "seed4242"

[namespace]
default = "echoes_of_the_void"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[writers]
"echoes_of_the_void" = ["echoes_of_the_void-game"]

